Kodat i mörkret. kikar vidare imorgon. men nåt sånthär typ...
swacedigital/branchio-flutter pull request #1
Opened 2020-02-03 19:36 UTC by nikokon

2020-02-03 19:44 UTC, elliotrask commented on android/src/main/java/se/swacedigital/branchio/BranchioPlugin.java
> +    Branch.getInstance().reInitSession(this.activity, branchReferralInitListener);
skulle activity kunna vara null här?

2020-02-04 06:32 UTC, oshtman commented on android/src/main/java/se/swacedigital/branchio/BranchioPlugin.java
> +    Branch.getInstance().reInitSession(this.activity, branchReferralInitListener);
☝️

2020-02-04 06:35 UTC, oshtman requested changes

2020-02-04 06:35 UTC, oshtman commented on android/src/main/java/se/swacedigital/branchio/BranchioPlugin.java
> +
Kan kanske vara värt att lyfta ut JSONObject - Hashmap mappningen till en egen metod och göra så att man kör `sink.success(jsonObjectToHash(referringParams))` och liknande för `failure`-clauset så eventuella lyssnare får parametrarna på init

2020-02-04 06:40 UTC, elliotrask commented on android/src/main/java/se/swacedigital/branchio/BranchioPlugin.java
> +    Branch.getInstance().reInitSession(this.activity, branchReferralInitListener);
Bör inte vara det då vi har en listener 🤔

2020-02-04 06:46 UTC, oshtman commented on android/src/main/java/se/swacedigital/branchio/BranchioPlugin.java
> +    Branch.getInstance().reInitSession(this.activity, branchReferralInitListener);
inte värt att chansa i java 😄

2020-02-04 16:52 UTC, merged